In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


# Background from Rodgers (2000), Chapter 1

The radiative transfer equation for upwelling infrared radiation at the top of the atmosphere (TOA) is given by:

$$L(\nu) = \int_{0}^{\infty} B_{\nu}[T(z)]\frac{d \tau(\nu,z)}{dz}dz $$

But Rodgers shows that this equation can be approximate by the following equation if one makes a series of measurements at frequencies ($\nu$) so that the frequency dependence of the Planck function can be neglected.

$$L_{i} = L(\nu_i) = \int_{0}^{\infty} B_{\nu}[T(z')]W_i(z')dz'$$

Rodgers uses the symbol L for radiance instead of I (which is used by Petty (2006)). So using Petty's symbols:

$$I_{i} = I(\nu_i) = \int_{0}^{\infty} B_{\nu}[T(z')]W_i(z')dz'$$


where W is the weighting function

$$ K_i(z) = \frac{d \tau(\nu,z)}{dz} $$

This the derivative of the atmospheric transmission with respect to altitude, z, at wavenumber, $ \nu $.

If one can determine $ B[T(z)] $ from this equation, then the temperature can easily be found by solving the Planck function for T. Thus, one should be able to determine the temperature profile in the atmosphere by measuring infrared radiances.

So typically in Inversion Theory, $ B[T(z)] $ would be expressed in linear form as:

$$B[\overline{\nu},T(z)] = \sum_{j=1}^{m} w_j M_j(z)$$

where $w_j$ is a set of coefficients to be determined and $M_j$ is a set of functions that describe the shape of B.

Combining these equations gives:

$$L_{i} = L(\nu_i) = \sum_{j=1}^{m} w_j \int_{0}^{\infty} M_j(z') W_i(z')dz' = \sum_{j=1}^{m} C_{ij} w_j$$

where C is 

$$C_{ij} = \int_{0}^{\infty} W_{j}(z) K_{i}(z) dz $$

C is a square matrix that describes m equations and m unknowns (which hopefully can be determined...).

Putting this altogether gives:

$$B[\overline{\nu},T(z)] = \sum_{i,j} M_j(z) C_{ij}^{-1} I_i = \sum_{i,j} G_i L_i$$

The bottom line is that to find $G_i$, one must invert the C matrix.  This is why the determination of the temperature profile from measured radiances is called <b><i>Inversion Theory</i></b>.

<b>BUT</b> there are serious issues with dealing with matrices as is explained below [by Twomey (1977)]. These relate to ill-conditioned matrices, having truly independent equations, and measurement noise.


## Basics of solving systems of equations using matrices

To solve a system of equations, one must solve 

$$Ax = B$$. 

To do this using matrices, one can determine x by inverting the matrix A. That is,

$$x = A^{-1}B$$

This is basically the same problem that has been laid out by both Twomey and Rodgers. But note that to solve for x, the equation must be "well-determined". That is, it must have a non-zero deteminant (the equations must be fully independent of each other), and not "contradictory" (free of noise). Unfortunately these conditions are never met when dealing with real measurements.

# From Twomey (1977), Chapter 2

## Section 2.1

### Algebraic elimination

Well behaved solution of 3 equations with 3 unknowns.

In [2]:
a = [[1., 1., 1.],[2., -1., 3.,],[3., 2., -1.]]
b = [2., 9., -1.]
solve(a,b)

array([ 1., -1.,  2.])

In [3]:
det(a)

13.0

Ill behaved solution of 3 equations with 3 unknowns.

In [4]:
a = [[1., 1., 1.],[2., -1., 3.,],[4., 1., 5.]]
b = [2., 9., 12.]
solve(a,b)

LinAlgError: Singular matrix

### Why did this solution fail?

Because the determinant equals 0 !!

In [5]:
det(a)

0.0

This matrix (a) is what is called singular.  The equations are not independent of each other.

Now find the determinant of the original matrix.

In [7]:
a = [[1., 1., 1.],[2., -1., 3.,],[3., 2., -1.]]

det(a)

13.0

Since it is non-zero, an easy solution is obtained.

### However, one cannot simply avoid issues in solving inverse problems by making sure that the determinant is non-zero.  Other conditions can occur with matrices that also cause problems.  For instance, the equations can be contradictory (e.g., due to noise in the measurements).

In [6]:
a = [[1., 1.], [2., 2.000001]]
b = [2., 4.000001]

solve(a,b)

array([1., 1.])

## But what if this is change only slightly.

In [7]:
a = [[1., 1.], [2., 2.000001]]
b = [2., 4.]

solve(a,b)

array([ 2., -0.])

A completely different solution is obtained...  This is bad news.

## or

In [8]:
a = [[1., 1.], [2., 2.]]
b = [2., 4.000001]

solve(a,b)

LinAlgError: Singular matrix

In [9]:
det(a)

0.0

This solution fails because the determinant is zero.

## or

In [10]:
a = [[1., 1.], [2., 2.]]
b = [2., 4.]

solve(a,b)

LinAlgError: Singular matrix

In [13]:
det(a)

0.0

Again, this fails because the equations are not independent, and the determinant equals zero.

## In summary...

## If there are m unknowns  and less than m equations, the system is <i>underdetermined</i>.

## If there are more than m equations and m unknowns, the system may be <i>overdetermined</i> only if there are m equations that at independent of each other.  When the equations are not independent, the system may be <i>overdetermined, determinate, or underdetermined</i>, depending on how many redundant equations are present.